### ISSUE TITLE
formatting done by vmd causes some lines to exceed character limit

### ISSUE THREAD

**Issue by pltrz** [bobertlo/vmd#2]
I noticed that in some special cases, when vmd formats indentation for things like lists, it can make some characters exceed the character limit, ideally it should recheck the character limit after making formatting changes.

An example with gibberish latin text:
```
- Accumsan dis tincidunt felis vivamus senectus, erat fermentum lacinia tempor condimentum euismod habitant sed molestie velit, id cum massa sagittis in platea porta class volutpat. Volutpat purus dui feugiat neque aliquam vehicula varius mattis vulputate ullamcorper, mus arcu senectus nascetur molestie cum venenatis et
```
becomes:
```
- Accumsan dis tincidunt felis vivamus senectus, erat fermentum lacinia tempor
   condimentum euismod habitant sed molestie velit, id cum massa sagittis in
   platea porta class volutpat. Volutpat purus dui feugiat neque aliquam vehicula
   varius mattis vulputate ullamcorper, mus arcu senectus nascetur molestie cum
   venenatis et
```

the word `vehicula` surpasses the character limit in this example by 2 characters.

Not sure if this is considered important or not but I noticed it on a few examples.

**Comment by bobertlo** [comment]
Thanks, I'm looking for correctness in this tool :) I'll look into that, I might have forgotten to include the prefix in the character count? I really only eyeball tested the column wrapping.

**Comment by bobertlo** [comment]
I'm not sure how those functions are effecting list items, but I found a couple small bugs in the linewrap library and that appears to have fixed this issues (copy and pasted your example.) I'll leave it open until I write actual tests.

**Comment by bobertlo** [comment]
Finally wrote these tests. Closing this, thanks again for catching that!
