### ISSUE TITLE
Formatting in links is silently deleted

### ISSUE THREAD

**Issue by mmnmnnmnmm** [bobertlo/vmd#4]
For example running vmd over this:

    [`code`](link)
    [**bold**](link)
    [*italic*](link)

Results in this:

    [](link) [](link) [](link)

**Comment by bobertlo** [comment]
I realize this and will fix it shortly. It hadn't come up because there has so far been no formatting in the void-docs repository. I don't see why code blocks would be used inside a link, but that's more of an editing decision.

**Comment by bobertlo** [comment]
I fixed this. Thank you for testing.
