### ISSUE TITLE
Behaviour when invoked without any options

### ISSUE THREAD

**Issue by pltrz** [bobertlo/vmd#5]
Seems like when `vmdfmt` is invoked without any options or files, it gets stuck. Perhaps when this is the case it should default to `vmdfmt -h` or something?

**Comment by bobertlo** [comment]
With no arguments it behaves the same as `gofmt`, reading from standard input. I guess that could be useful somehow. I would have added `-d`, but with the stated use case of this tool, it is just as easy to use `git diff`, so I did not implement that.. I don't understand what `vmdfmt -h` is supposed to be. I would consider replacing this option with `-` for stdin. But, I was going for compatibility with `gofmt`.

**Comment by pltrz** [comment]
> With no arguments it behaves the same as `gofmt`, reading from standard input. I guess that could be useful somehow. I would have added `-d`, but with the stated use case of this tool, it is just as easy to use `git diff`, so I did not implement that..

> I would consider replacing this option with `-` for stdin. But, I was going for compatibility with `gofmt`.

Gotcha. This all makes sense now. :+1: 

> I don't understand what `vmdfmt -h` is supposed to be.

I expected it to mean "help", ie. "show me available options". My thought was that it must be implemented somewhere considering if I invoke a random and meaningless flag such as `vmdfmt -z`, it outputs `flag provided but not defined: -z ...` but `vmdfmt -h` doesn't give this message. Maybe that behaviour is from the `flag` package?
