### ISSUE TITLE
codeblock inside of blockquotes broken - AKA Unsupported node type HTMLSpan ignored

### ISSUE THREAD

**Issue by pltrz** [bobertlo/vmd#7]
When parsing the following text, `vmdfmt` throws an error:

`error: Unsupported node type HTMLSpan ignored`

    $ cat test.md
    > Note: By default, IWD can be controlled by the root user or those in the `wheel` group.
    >
    > ```
    > # gpasswd -a <user> wheel
    > ```
    >

    ```
    $ iwctl

    [iwd]# help
                               Available commands
    --------------------------------------------------------------------------------
      Commands                                          Description
    --------------------------------------------------------------------------------

    Adapters:
      adapter list                                      List adapters
      adapter <phy> show                                Show adapter info
      adapter <phy> set-property <name> <value>         Set property
    ...
    ```

When removing the codeblock and testing just the blockquote, or vice versa it parses with no error. I don't know where the source of this issue comes from.

**Comment by bobertlo** [comment]
It looks like this is another upstream bug. I have no idea how in this case it doesn't work, because I made tests with codeblocks inside blockquotes, but I'm getting this from blackfriday (via bfdump)

`````
  BlockQuote
    Paragraph
      Text "Note: By default, IWD can be controlled by the root user or those in the "
      Code: `wheel`
      Text " group."
    CodeBlock: Fenced: true Level: 3
{
>  gpasswd -a <user> wheel
> ```
> 
> 
`````

I'll look into this more, but it's not looking great for codeblocks inside of blockquotes, unless a new markdown parser is used.

**Comment by bobertlo** [comment]
for reference, it should look like this:
`````
Document
  BlockQuote
    Paragraph
      Text "Note: This is a blockquote"
    CodeBlock: Fenced: true Level: 3
{
# This is a codeblock
}

`````
